# Example configuration file
# Rename to config.yaml and fill in your values

database:
  host: "your_db_host"
  port: 3306
  user: "your_username"
  password: "your_password"
  name: "your_database_name"

server:
  port: 8080
  host: "0.0.0.0" 